spring.application.name=gateway
server.port=8081

# Development configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/calendar-app
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/calendar-app/protocol/openid-connect/certs
users.api.url=http://localhost:8082
social.api.url=http://localhost:8083
chat.api.url=http://localhost:8084
chat.rsocket.url=ws://localhost:8084

# CORS allowed origin for dev
cors.allowed.origin=http://localhost:4200

logging.level.reactor.netty=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
logging.level.reactor.core=DEBUG
media.api.url=http://localhost:8085
