# Development profile for local testing
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/calendar-app
users.api.url=http://localhost:8082
social.api.url=http://localhost:8083
chat.api.url=http://localhost:8084
chat.rsocket.url=ws://localhost:8084
