spring.application.name=gateway
server.port=8081

# Production/Base configuration (values injected by Kube)
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_INTERNAL_JWK_SET_URI}
users.api.url=${USERS_API_URL}
social.api.url=${SOCIAL_API_URL}
chat.api.url=${CHAT_API_URL}
chat.rsocket.url=${CHAT_RSOCKET_URL}
media.api.url=${MEDIA_API_URL}

logging.level.reactor.netty=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
logging.level.reactor.core=DEBUG
